name: Build CN Image

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: Prod-CN
    env:
      REVALIDATE_TOKEN: ${{ secrets.XATA_API_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      ENABLE_TRACK: ${{ vars.ENABLE_TRACK }}
      NEXT_PUBLIC_REGION: ${{ vars.NEXT_PUBLIC_REGION }}
      NEXT_PUBLIC_WEBSITE_URL: ${{vars.NEXT_PUBLIC_WEBSITE_URL}}
      FEC_API_TOKEN: ${{vars.FEC_API_TOKEN}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Qcloud Hongkong Container Registry
        uses: docker/login-action@v3
        with:
          registry: hkccr.ccs.tencentyun.com
          username: "${{ vars.QCLOUD_REGISTRY_USERNAME }}"
          password: "${{ secrets.QCLOUD_REGISTRY_PASSWORD }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Env
        run: |
          touch .env
          echo REVALIDATE_TOKEN="$REVALIDATE_TOKEN" >> .env
          echo SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN" >> .env
          echo NEXT_PUBLIC_ENABLE_TRACK="$ENABLE_TRACK" >> .env
          echo NEXT_PUBLIC_REGION="$NEXT_PUBLIC_REGION" >>.env
          echo NEXT_PUBLIC_WEBSITE_URL="$NEXT_PUBLIC_WEBSITE_URL" >>.env
          echo FEC_API_TOKEN="$FEC_API_TOKEN" >>.env

      - name: Build and push
        uses: docker/build-push-action@v6
        timeout-minutes: 5
        with:
          context: .
          push: true
          tags: |
            hkccr.ccs.tencentyun.com/furrycons/frontend:latest
            hkccr.ccs.tencentyun.com/furrycons/frontend:${{ github.sha }}

      - name: Call Webhook
        run: |
          curl -X POST ${{ vars.WEBHOOK_URL }} \
            -H "Content-Type: application/json"
